### ISSUE TITLE
Create, populate and share an OpenFisca key pass

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-ops#27]
In response to [incident learning review](https://docs.google.com/document/d/1MXlThS27SVjF4yjPiSQDkcSwoQoz2X6-9Zc8p5wtXdc/edit?usp=sharing), and aimed to improve operational resilience:

- [x] Create an OpenFisca key pass - parent #36 

Add the following accounts:

## Comptes org

- [x] OVH @maukoquiroga
- [x] Gandi @Anna-Livia 
- [x] Openfisca bot (GitHub) @fpagnoux 
- [x] Twitter - parent #36 
- [x] Buffer - parent #36
- [x] stats.data.gouv.fr @Anna-Livia 

## Comptes perso (list who has access)

- [x] Pypi @Anna-Livia @fpagnoux @sandcha 
- [x] ~Facebook~ (no account)
- [ ] pfa.data.gouv.fr @Anna-Livia 
- [ ] Slack
- [ ] Clés SSH pour openfisca@openfisca.fr @fpagnoux @Anna-Livia @sandcha
- [ ] Clés SSH pour et root@openfisca.fr @fpagnoux @Anna-Livia @sandcha  (sudoers) 
- [ ] DockerHub @benjello

## Don't know if org or perso

- [x] Uptime robot
- [ ] letsencrypt @cbenz => I don't think letsencrypt uses login/password
- [x] Saucelabs

## Then

- [x] Publish comptes org - parent #38
- [ ] Publish comptes perso
- [x] Who has the keepass? - parent #36 
- [ ] How do we do for personal accounts ?
- [x] And publish the keypass on openfisca/openfisca-ops - parent #36

**Comment by Anna-Livia** [comment]
+ Slack 
+ clés SSH pour openfisca@openfisca.fr et root@openfisca.fr
+ Saucelabs
+ Uptime robot

**Comment by fpagnoux** [comment]
Do we  even have a Facebook account?

For slack and ssh, and other situations where we rely on a personal accounts/keys, one solution I can see is to introduce backup admin users with admin rights/root access. 

This way if all the current human admins are on a trip to Mars, someone with access to the keypass could still log in and do what they need.

**Comment by fpagnoux** [comment]
> letsencrypt @fpagnoux @cbenz

I don't have the password for letsencrypt

**Comment by maukoquiroga** [comment]
> Do we even have a Facebook account?

At this stage I think it is more an urban legend

> For slack and ssh, and other situations where we rely on a personal accounts/keys, one solution I can see is to introduce backup admin users with admin rights/root access.

Sounds like a good idea, thanks!
